sudo: required
languange: generic
services:
    - docker

before_install:
    - docker build -t jeroenvanderzwam/docker -f Dockerfile.dev .

script:
    - docker run -e CI=true jeroenvanderzwam/docker npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docer-env" 
    bucket_name: "elasticbeanstalk-us-east-2-000335204593"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY